import type { NavLink, Service } from '@/types'

// Site Configuration
export const SITE_CONFIG = {
  name: 'Ripple Roofing & Construction',
  description: 'Premium Roofing Services in Central Texas',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://rippleroofs.com',
  phone: '(512) 763-5277',
  phoneRaw: '5127635277',
  email: 'info@rippleroofs.com',
  address: '1000 Heritage Center Circle, #165, Round Rock, TX 78664',
  city: 'Round Rock',
  state: 'Texas',
  zip: '78664',
  hours: '24/7 Emergency Service Available',
  serviceArea: 'Central Texas, Austin Metro, San Antonio, Georgetown, Round Rock, Killeen, Copperas Cove, Portland',
  certifications: ['CertainTeed Shingle Master', 'Fully Insured'],
  social: {
    facebook: 'https://facebook.com/rippleroofs',
    instagram: 'https://www.instagram.com/ripple_roofing/',
    linkedin: 'https://www.linkedin.com/company/ripple-roofing',
    twitter: '',
    youtube: '', // Coming soon
    tiktok: '', // Coming soon
    googleBusiness: 'https://share.google/SsBLQ1RNm8ZQ7rFrk',
    nextdoor: 'https://nextdoor.com/page/ripple-roofing-construction/',
  },
}

// Navigation Links
export const NAV_LINKS: NavLink[] = [
  { href: '/', label: 'Home' },
  { 
    href: '/services', 
    label: 'Services',
    children: [
      { href: '/services/residential-roofing', label: 'Residential Roofing' },
      { href: '/services/commercial-roofing', label: 'Commercial Roofing' },
      { href: '/services/roof-replacement', label: 'Roof Replacement' },
      { href: '/services/roof-repairs', label: 'Roof Repairs' },
      { href: '/services/emergency-services', label: 'Emergency Services' },
      { href: '/services/roof-inspection', label: 'Roof Inspection' },
      { href: '/services/stone-coated-steel-roofing', label: 'Stone-Coated Steel Roofing' },
      { href: '/services/gutter-installation', label: 'Gutter Installation' },
      { href: '/services/storm-damage-restoration', label: 'Storm Damage Restoration' },
      { href: '/services/insurance-claim-documentation', label: 'Insurance Claim Documentation' },
      { href: '/services/roof-maintenance', label: 'Roof Maintenance Plans' },
      { href: '/services/siding-installation', label: 'Siding Installation & Repair' },
      { href: '/services/attic-ventilation', label: 'Attic Ventilation & Insulation' },
      { href: '/services/pergolas', label: 'Pergola Construction' },
      { href: '/services/paintless-dent-repair', label: 'Paintless Dent Repair (PDR)' },
    ]
  },
  {
    href: '/locations',
    label: 'Locations',
    children: [
      { href: '/locations/round-rock', label: 'Round Rock' },
      { href: '/locations/austin', label: 'Austin' },
      { href: '/locations/pflugerville', label: 'Pflugerville' },
      { href: '/locations/cedar-park', label: 'Cedar Park' },
      { href: '/locations/leander', label: 'Leander' },
      { href: '/locations/georgetown', label: 'Georgetown' },
      { href: '/locations/hutto', label: 'Hutto' },
      { href: '/locations/manor', label: 'Manor' },
      { href: '/locations/jarrell', label: 'Jarrell' },
      { href: '/locations/san-marcos', label: 'San Marcos' },
      { href: '/locations/new-braunfels', label: 'New Braunfels' },
      { href: '/locations/san-antonio', label: 'San Antonio' },
      { href: '/locations/temple', label: 'Temple' },
      { href: '/locations/killeen', label: 'Killeen' },
      { href: '/locations/copperas-cove', label: 'Copperas Cove' },
      { href: '/locations/waco', label: 'Waco' },
    ]
  },
  { href: '/projects', label: 'Projects' },
  { 
    href: '/resources', 
    label: 'Resources',
    children: [
      { href: '/calculators', label: 'Roofing Calculators' },
      { href: '/resources/material-comparison-tool', label: 'Material Comparison Tool' },
      { href: '/resources/roof-inspection-checklist', label: 'Free Roof Inspection Checklist' },
      { href: '/resources/storm-damage-insurance-guide', label: 'Insurance Claim Guide' },
      { href: '/resources/material-comparison-chart', label: 'Material Comparison Chart' },
      { href: '/resources/seasonal-maintenance-calendar', label: 'Seasonal Maintenance Calendar' },
      { href: '/blog', label: 'Roofing Blog' },
    ]
  },
  { href: '/about', label: 'About' },
  { href: '/financing', label: 'Financing' },
  { href: '/faq', label: 'FAQ' },
  { href: '/contact', label: 'Contact' },
]

// Services Data
export const SERVICES: Service[] = [
  {
    id: '1',
    title: 'Residential Roofing',
    slug: 'residential-roofing',
    shortDescription: 'Complete residential roofing servicesâ€”installation, repair, replacement, and maintenance for Central Texas homes.',
    description: 'Your home is your family\'s sanctuary and your largest investment. Ripple Roofing & Construction provides comprehensive residential roofing services for homeowners throughout Central Texasâ€”from simple repairs to complete roof replacements. As CertainTeed Shingle Master certified contractors, we offer expert installation of all roofing types: architectural shingles, impact-resistant shingles, metal roofing, tile, and specialty materials. We serve Round Rock, Austin, Georgetown, and surrounding communities with honest assessments, quality craftsmanship, and warranties that protect your investment. Whether you need emergency storm repairs, routine maintenance, or a brand new roof, we treat your home like our own. Free inspections, transparent pricing, and 10-year workmanship warranty on all installations.',
    icon: 'ðŸ ',
    image: '/images/services/residential-roofing.jpg',
    process: [
      { step: 1, title: 'Free Roof Inspection & Assessment', description: 'We thoroughly inspect your roof\'s condition, identify any issues, document with photos, and assess remaining lifespan. Whether you need minor repairs or full replacement, we provide honest recommendations. Free inspections after major storms!' },
      { step: 2, title: 'Detailed Consultation & Material Selection', description: 'We explain your options clearlyâ€”shingle types, metal roofing, tile, impact-resistant materialsâ€”with pros, cons, costs, and warranties. We help you choose materials that fit your home style, budget, and Central Texas climate needs.' },
      { step: 3, title: 'Transparent Written Estimate', description: 'You receive a detailed, itemized quote with no hidden fees or surprise charges. We explain every line item, timeline expectations, and warranty coverage. We help with insurance claims if storm damage is involved.' },
      { step: 4, title: 'Professional Installation', description: 'Our certified crews arrive on time with all materials and equipment. We protect your property, follow manufacturer specifications precisely, maintain a clean work site, and complete most projects in 1-3 days. Daily progress updates keep you informed.' },
      { step: 5, title: 'Quality Inspection & Warranty Activation', description: 'We conduct a final walkthrough with you, perform magnetic nail sweep, clean up completely, and activate your manufacturer material warranty plus our 10-year workmanship warranty. You get copies of all documentation for your records.' },
    ],
    benefits: [
      'CertainTeed Shingle Master Certified contractors',
      'All roofing types: shingles, metal, tile, specialty',
      'Free inspectionsâ€”no obligation quotes',
      'Impact-resistant shingles for hail protection',
      'Insurance claim assistance and documentation',
      'Financing options available (various terms)',
      '10-year workmanship warranty on installations',
      'Manufacturer warranties: 25-50 year coverage',
      'Serving Central Texas: Round Rock, Austin, Georgetown',
      'Emergency storm repairsâ€”24/7 availability',
      'Transparent pricingâ€”no hidden fees',
      'Projects completed in 1-3 days typically',
    ],
  },
  {
    id: '2',
    title: 'Commercial Roofing',
    slug: 'commercial-roofing',
    shortDescription: 'Professional commercial roofing for businessesâ€”flat roofing systems, TPO, EPDM, metal, and preventative maintenance plans.',
    description: 'Your commercial roof protects your business, inventory, equipment, and livelihood. Ripple Roofing & Construction provides comprehensive commercial roofing services for businesses throughout Central Texasâ€”from flat roof installations to ongoing maintenance programs. We specialize in flat roofing systems (TPO, EPDM, modified bitumen), metal roofing, and commercial roof coatings. Whether you own retail space, office buildings, warehouses, apartment complexes, or industrial facilities in Round Rock, Austin, Georgetown, or surrounding areas, we minimize business disruption while delivering quality work. We work after-hours or weekends when needed, provide detailed warranties, and offer preventative maintenance plans that extend roof life and prevent costly emergency repairs. Fully certified, insured, and experienced with all commercial roofing systems.',
    icon: 'ðŸ¢',
    image: '/images/services/commercial-roofing.jpg',
    process: [
      { step: 1, title: 'Free Commercial Roof Assessment', description: 'We conduct a thorough inspection of your commercial roof, identify issues, assess remaining lifespan, document with photos/measurements, and provide written evaluation. We work around your business hours and provide detailed reports within 24-48 hours.' },
      { step: 2, title: 'Customized Solution & Proposal', description: 'We design a solution tailored to your property type, budget, and timeline. Options include full replacement, roof restoration/coating, or targeted repairs. Detailed written proposal with material specs, timeline, and transparent pricing. We explain ROI and financing options.' },
      { step: 3, title: 'Minimal-Disruption Installation', description: 'We schedule work to minimize impact on your operationsâ€”after hours, weekends, or phased approach. Professional crews arrive on time with all equipment. We protect your property, maintain safety protocols, and keep you updated daily on progress.' },
      { step: 4, title: 'Quality Assurance & Documentation', description: 'Final inspection ensures code compliance and quality standards. Complete cleanup, documentation photos, warranty registration, and maintenance recommendations. We provide copies of all permits, inspections, and warranty documents for your records.' },
      { step: 5, title: 'Preventative Maintenance Programs', description: 'Optional maintenance plans include bi-annual inspections, minor repairs, drainage cleaning, and detailed condition reports. Catch small issues before they become expensive emergencies. Extends roof life 5-10 years and maintains warranty validity.' },
    ],
    benefits: [
      'All flat roofing systems: TPO, EPDM, modified bitumen',
      'Metal roofing for commercial applications',
      'Roof coating and restoration services',
      'After-hours and weekend scheduling available',
      'Minimal business disruption guarantee',
      'Detailed proposals with transparent pricing',
      'Preventative maintenance programs',
      'Emergency repair responseâ€”24/7 availability',
      'Fully certified and insured for commercial work',
      '10-year workmanship warranty',
      'Manufacturer warranties: 10-30 years',
      'Serving Central Texas businesses',
    ],
  },
  {
    id: '3',
    title: 'Roof Replacement',
    slug: 'roof-replacement',
    shortDescription: 'Expert roof replacement services in Central Texas. From material selection to installation, we guide you through every step with transparency and craftsmanship.',
    description: 'When it\'s time for a new roof, Ripple Roofing & Construction guides you through the process with expertise and transparency. As a CertainTeed Shingle Master certified contractor, we offer premium roofing materials specifically chosen for Central Texas\'s challenging climateâ€”intense heat, severe storms, and hail. Whether your roof has reached the end of its lifespan, sustained storm damage, or you\'re upgrading for energy efficiency and curb appeal, we provide comprehensive roof replacement services with industry-leading warranties. Serving Round Rock, Austin, Georgetown, and all of Central Texas, we\'ve helped thousands of homeowners protect their most valuable investment with quality craftsmanship and honest service.',
    icon: 'ðŸ”„',
    image: '/images/services/roof-replacement.jpg',
    process: [
      { step: 1, title: 'Free Comprehensive Inspection', description: 'We conduct a thorough 50-point inspection of your existing roof, identifying all issues, potential concerns, and underlying problems. We document everything with photos and provide a detailed written report.' },
      { step: 2, title: 'Material Selection & Consultation', description: 'We guide you through material options including architectural shingles, impact-resistant shingles, metal roofing, and tile. We explain pros/cons, costs, warranties, and what works best for your specific home, budget, and neighborhood.' },
      { step: 3, title: 'Detailed Written Estimate', description: 'You receive a transparent, itemized estimate with no hidden fees. We explain every line item, timeline expectations, and payment terms. We help you understand insurance coverage if applicable and financing options available.' },
      { step: 4, title: 'Project Preparation', description: 'We handle all permits and HOA approvals. We protect your property with tarps and barriers, coordinate material delivery, and provide a detailed project timeline. Your project manager will be your single point of contact throughout.' },
      { step: 5, title: 'Expert Installation', description: 'Our certified crews arrive on schedule and complete most replacements in 1-3 days. We use premium materials, follow manufacturer specifications precisely, and maintain a clean, safe work site. Daily progress updates keep you informed.' },
      { step: 6, title: 'Quality Inspection & Cleanup', description: 'We conduct a final walkthrough with you, ensuring complete satisfaction. Our magnetic sweep removes all nails and debris. We leave your property cleaner than we found it, with professional disposal of all materials.' },
      { step: 7, title: 'Warranty Activation & Follow-Up', description: 'We register your warranty with the manufacturer, provide all documentation, and schedule a follow-up inspection after your first rain. We\'re here for the life of your roof with ongoing support and maintenance.' },
    ],
    benefits: [
      'CertainTeed Shingle Master Certifiedâ€”elite contractor status with enhanced warranties',
      'Premium materials rated for Texas heat, hail, and high winds',
      'Transparent pricing with detailed, itemized estimates',
      'Most projects completed in 1-3 days with minimal disruption',
      'Comprehensive warranties on both materials (25-50+ years) and workmanship (10 years)',
      'Insurance claim assistance including adjuster meetings and documentation',
      'Flexible financing options with approved credit',
      'Thorough cleanup including magnetic nail sweep',
      'Local Central Texas companyâ€”not storm chasers, here for the long term',
      'A+ BBB rating with hundreds of satisfied customers',
      'Free inspections after severe weather events',
      '24/7 emergency service availability',
    ],
  },
  {
    id: '4',
    title: 'Roof Repairs',
    slug: 'roof-repairs',
    shortDescription: 'Fast, reliable roof repairs that stop leaks and prevent costly damage.',
    description: 'Don\'t let a small roof problem become a big expense. Our expert roof repair services in Round Rock, Austin, and Georgetown address everything from minor leaks and missing shingles to storm damage and flashing issues. As a CertainTeed Shingle Master certified contractor, we use premium materials and proven techniques to restore your roof\'s integrity. Most repairs are completed in just a few hours, with same-day service available. We provide honest assessmentsâ€”if repair isn\'t the best option, we\'ll tell you. Our 10-year workmanship warranty backs every repair we make.',
    icon: 'ðŸ”§',
    image: '/images/services/roof-repairs.jpg',
    process: [
      { step: 1, title: 'Free Inspection & Diagnosis', description: 'Thorough evaluation to identify all issues, not just visible damage. We check for underlying problems that could worsen. Honest assessment of whether repair or replacement is more cost-effective.' },
      { step: 2, title: 'Detailed Photo Documentation', description: 'We document all damage with photos and notes for your records and insurance claims. Clear explanation of what needs fixing and why.' },
      { step: 3, title: 'Transparent Pricing', description: 'Upfront pricing with no surprises. Itemized quote showing materials and labor. We work directly with insurance companies if storm damage is involved.' },
      { step: 4, title: 'Professional Repair', description: 'Experienced crews complete most repairs in 2-4 hours. We match existing materials for seamless appearance. All work meets manufacturer specifications and local building codes.' },
      { step: 5, title: 'Quality Inspection', description: 'Final walkthrough to ensure repair quality. We test for leaks and verify structural integrity. Magnetic nail sweep of work area.' },
      { step: 6, title: '10-Year Workmanship Warranty', description: 'Every repair backed by our comprehensive workmanship warranty. If the repaired area has issues, we fix it at no charge.' },
    ],
    benefits: [
      'Same-day and emergency repair services available',
      'CertainTeed Shingle Master certified technicians',
      'Premium Texas-rated materials that match existing roof',
      'Complete in 2-4 hours for most repairs',
      '10-year workmanship warranty on all repairs',
      'Insurance claim assistance and documentation',
      'Honest assessmentsâ€”we\'ll tell you if replacement is better',
      'No hidden fees or surprise charges',
      'Free inspections after major storms',
      'Local company serving Central Texas since [year]',
      'A+ BBB rating with hundreds of satisfied customers',
      '24/7 emergency service for urgent situations',
    ],
  },
  {
    id: '5',
    title: 'Emergency Services',
    slug: 'emergency-services',
    shortDescription: '24/7 emergency roofing responseâ€”we\'re there when you need us most.',
    description: 'Roof emergencies don\'t wait for business hours. When storms hit, trees fall, or sudden leaks threaten your home, we respond immediatelyâ€”24 hours a day, 7 days a week, 365 days a year. Our emergency roofing services serve Round Rock, Austin, Georgetown, and all Central Texas with rapid response times (typically 2-4 hours). We provide emergency tarping to stop water intrusion, assess damage for insurance claims, and coordinate permanent repairs. Whether it\'s 2 PM or 2 AM, our certified crews are ready to protect your home and minimize damage. Call (512) 763-5277 anytime for immediate emergency assistance.',
    icon: 'ðŸš¨',
    image: '/images/services/emergency-services.jpg',
    process: [
      { step: 1, title: '24/7 Emergency Call & Dispatch', description: 'Call (512) 763-5277 anytime. We answer immediatelyâ€”no voicemail, no waiting. Our dispatcher gathers essential information and sends the nearest crew. Average response time: 2-4 hours depending on location and weather conditions.' },
      { step: 2, title: 'Immediate Emergency Tarping', description: 'Our crew arrives with heavy-duty tarps, securing materials, and safety equipment. We quickly cover damaged areas to stop water intrusion and prevent further damage to your home, belongings, and structure. Your home is protected within 30-60 minutes of arrival.' },
      { step: 3, title: 'Damage Assessment & Documentation', description: 'Once your home is secure, we conduct a thorough assessment of all damage. We document everything with photos for insurance claims, identify safety hazards, and determine the scope of permanent repairs needed.' },
      { step: 4, title: 'Insurance Coordination', description: 'We help you contact your insurance company, provide documentation they need, and schedule adjuster visits. Our reports are insurance-acceptable and comprehensive. We can attend adjuster meetings with you.' },
      { step: 5, title: 'Permanent Repair Plan', description: 'We provide a detailed estimate for permanent repairs, timeline expectations, and material options. No pressureâ€”you decide when to proceed. Emergency tarping buys you time to make informed decisions.' },
      { step: 6, title: 'Complete Restoration', description: 'When you\'re ready, our certified crews complete all permanent repairs using premium materials. We restore your roof to full integrity, backed by our 10-year workmanship warranty.' },
    ],
    benefits: [
      '24/7/365 availabilityâ€”we answer every call',
      'Rapid 2-4 hour response time in Central Texas',
      'Immediate emergency tarping to stop water damage',
      'Heavy-duty professional-grade tarps and securing',
      'Complete damage documentation for insurance',
      'Insurance claim assistance and adjuster coordination',
      'Safety hazard identification and mitigation',
      'Certified, experienced emergency response crews',
      'Transparent emergency service pricing',
      'Permanent repair coordination when you\'re ready',
      '10-year workmanship warranty on repairs',
      'Local company serving Round Rock, Austin, Georgetown',
    ],
  },
  {
    id: '6',
    title: 'Roof Inspection & Assessment',
    slug: 'roof-inspection',
    shortDescription: 'Comprehensive 50-point roof inspections with detailed photo reports.',
    description: 'Knowledge is power when it comes to your roof. Our comprehensive roof inspections provide you with a complete understanding of your roof\'s conditionâ€”whether you\'re buying a home, selling a property, concerned about storm damage, or simply want peace of mind. As CertainTeed Shingle Master certified contractors, we conduct thorough 50-point inspections of every roof component. You receive a detailed photo report with condition ratings, remaining lifespan estimates, and prioritized repair recommendations. We serve homeowners in Round Rock, Austin, Georgetown, and all Central Texas. Most inspections are completed in 45-60 minutes. Free inspections after major storms!',
    icon: 'ðŸ”',
    image: '/images/services/roof-inspection.jpg',
    process: [
      { step: 1, title: 'Schedule Your Inspection', description: 'Quick online booking or call (512) 763-5277. We offer flexible scheduling including evenings and weekends. Free inspections after major storms or for insurance claims.' },
      { step: 2, title: 'Comprehensive 50-Point Inspection', description: 'Our certified technician examines all roof components: shingles, flashing, valleys, penetrations, gutters, ventilation, underlayment visibility, structural integrity. We use drone photography for steep or complex roofs. Takes 45-60 minutes.' },
      { step: 3, title: 'Detailed Photo Report', description: 'You receive a comprehensive report with photos of every issue, condition ratings (1-10 scale), remaining lifespan estimates, and repair priority levels (immediate, near-term, monitor). Sent via email within 24 hours.' },
      { step: 4, title: 'Review & Consultation', description: 'We walk through findings with you in person or by phone. No pressureâ€”just honest recommendations. If repairs are needed, we provide transparent pricing. If your roof is fine, we tell you that too!' },
      { step: 5, title: 'Optional Follow-Up', description: 'We can schedule repairs, provide quotes for replacement if needed, or simply schedule your next routine inspection. All findings documented for your records and future reference.' },
    ],
    benefits: [
      'Comprehensive 50-point inspection checklist',
      'Detailed photo report with condition ratings',
      'Certified CertainTeed Shingle Master inspectors',
      'Drone photography for steep/complex roofs',
      'Completed in 45-60 minutes',
      'Free post-storm inspections',
      'Insurance claim documentation assistance',
      'Pre-purchase home inspection reports',
      'Annual maintenance inspection programs',
      'Honest assessmentsâ€”no pressure sales',
      'Remaining lifespan estimates for planning',
      '24-hour report turnaround',
    ],
  },
  {
    id: '7',
    title: 'Gutter Installation',
    slug: 'gutter-installation',
    shortDescription: 'Professional seamless gutter installationâ€”5" and 6" systems that protect your foundation.',
    description: 'Your gutters are your home\'s first line of defense against water damage. Professional gutter installation protects your foundation, prevents basement flooding, eliminates soil erosion, and preserves your landscaping. We install seamless aluminum gutters custom-fabricated on-site to fit your home perfectlyâ€”no leaky seams every 10 feet like sectional gutters. Choose from 5-inch standard systems (most homes) or 6-inch high-capacity systems (large roofs, heavy rainfall areas). We serve Round Rock, Austin, Georgetown, and all Central Texas with 20+ color options to match any home. Our gutters come with a 20-year material warranty and 10-year workmanship warranty. Typical installation completed in 1 day!',
    icon: 'ðŸ’§',
    image: '/images/services/gutter-installation.jpg',
    process: [
      { step: 1, title: 'Free Assessment & Measurement', description: 'We measure your roofline, evaluate drainage needs, assess downspout placement for optimal water flow, check fascia condition, and identify problem areas. You choose gutter size (5" or 6"), color (20+ options), and optional gutter guards.' },
      { step: 2, title: 'Custom Fabrication On-Site', description: 'We bring our seamless gutter machine to your home and custom-fabricate gutters to your exact measurements. No seams except at cornersâ€”means no leaks! Available in .027 or .032 gauge aluminum (thicker = more durable).' },
      { step: 3, title: 'Professional Installation', description: 'We remove old gutters if needed (disposal included), repair fascia if damaged, install seamless gutters with hidden hangers every 24 inches, properly pitch gutters for drainage (1/4" per 10 feet), install downspouts with extensions, and seal all connections.' },
      { step: 4, title: 'Testing & Final Inspection', description: 'We run water through entire system to verify proper flow and drainage, check all connections for leaks, ensure downspouts direct water 4-6 feet from foundation, clean up all debris, and provide maintenance tips. Typically completed in 1 day!' },
      { step: 5, title: 'Warranty & Maintenance Options', description: '20-year material warranty on gutters, 10-year workmanship warranty on installation. Optional: gutter guard installation (keeps leaves out), annual cleaning service programs, and routine inspection packages.' },
    ],
    benefits: [
      'Seamless guttersâ€”no leaky joints every 10 feet',
      'Custom-fabricated on-site for perfect fit',
      '5-inch or 6-inch systems available',
      '20+ color options to match your home',
      'Hidden hanger systemâ€”clean appearance',
      '.027 or .032 gauge aluminum (thicker options)',
      'Foundation protection prevents $10k-$50k repairs',
      'Prevents basement flooding and moisture',
      'Eliminates soil erosion around home',
      'Protects landscaping and flower beds',
      '20-year material + 10-year workmanship warranty',
      'Most homes completed in 1 day',
    ],
  },
  {
    id: '8',
    title: 'Storm Damage Restoration',
    slug: 'storm-damage-restoration',
    shortDescription: 'Expert storm damage assessment and restorationâ€”we handle insurance claims, emergency repairs, and complete restoration.',
    description: 'Central Texas storms bring hail, high winds, fallen trees, and flying debris that can devastate your roof. Storm damage restoration requires specialized expertiseâ€”identifying hidden damage that untrained eyes miss, documenting everything for insurance claims, working with adjusters to maximize coverage, and executing repairs to full manufacturer warranty standards. We respond within 2 hours for emergency tarping and immediate protection, conduct comprehensive damage assessments using drones and thermal imaging, handle all insurance paperwork and adjuster meetings, and restore your roof to better-than-before condition. We serve Round Rock, Austin, Georgetown, and all Central Texas. Our storm specialists have documented over 2,000 insurance claims and recovered millions in rightful coverage for homeowners. Most insurance claims cover 100% of roof replacement minus deductibleâ€”we ensure you get what you deserve.',
    icon: 'â›ˆï¸',
    image: '/images/services/storm-damage.jpg',
    process: [
      { step: 1, title: 'Emergency Response & Immediate Protection', description: 'We respond within 2 hours for emergency situations. Our crew performs emergency tarping to prevent interior water damage, documents all damage with photos and video, secures loose materials, identifies safety hazards, and provides immediate stability. Available 24/7 for storm emergencies.' },
      { step: 2, title: 'Comprehensive Damage Assessment', description: 'We conduct a thorough inspection using drones for aerial documentation, thermal imaging to detect hidden moisture, measure hail impacts and wind damage, check for structural issues, inspect gutters and flashing, document every detail for insurance, and create a complete scope of work with pricing.' },
      { step: 3, title: 'Insurance Claims Management', description: 'We handle the entire insurance processâ€”file your claim, schedule adjuster meeting, meet adjuster on-site and advocate for full coverage, document all damage with professional reports, fight for proper scope if needed (supplements), negotiate fair settlements, and ensure you maximize your coverage. We work with all insurance companies.' },
      { step: 4, title: 'Complete Restoration Work', description: 'Once your claim is approved, we execute full restorationâ€”remove damaged roofing materials, replace damaged decking and structure if needed, install new underlayment and ice/water shield, install new shingles to manufacturer specs, replace damaged gutters and flashing, upgrade ventilation if needed (often covered), and restore roof to better-than-before condition.' },
      { step: 5, title: 'Final Inspection & Warranty Protection', description: 'We conduct final quality inspection, ensure all work meets manufacturer warranty requirements, provide complete documentation for your records and insurance, verify proper ventilation and installation, clean up all debris with magnet sweep, and activate your 50-year shingle warranty + our 10-year workmanship warranty. Your roof is now fully protected!' },
    ],
    benefits: [
      'Emergency response within 2 hoursâ€”24/7 availability',
      'Expert insurance claims managementâ€”maximize coverage',
      'Drone & thermal imaging documentation',
      'Work with ALL insurance companies',
      '2,000+ successful claimsâ€”millions recovered',
      'Free damage assessment & inspection',
      'Meet with adjusterâ€”fight for proper scope',
      'Handle supplements & negotiations',
      'Most claims cover 100% minus deductible',
      'Upgrade opportunities often covered by insurance',
      'Full restoration to manufacturer standards',
      '50-year shingle + 10-year workmanship warranty',
    ],
  },
  {
    id: '9',
    title: 'Insurance Claim Documentation',
    slug: 'insurance-claim-documentation',
    shortDescription: 'Professional roof damage documentation and adjuster supportâ€”we help homeowners present accurate information for their insurance claims.',
    description: 'After a storm damages your roof, your insurance company needs accurate documentation to process your claim. We provide professional damage inspection, detailed documentation with photos and measurements, and expert support during the adjuster\'s visitâ€”all at no cost to you. Our role is simple: document roof damage thoroughly and work cooperatively with your insurance adjuster to ensure all damage is properly identified and noted. YOU remain in control of your claimâ€”we simply provide the roofing expertise. We don\'t file claims, negotiate settlements, or act as public adjusters (which requires a special license in Texas). We DO inspect your roof professionally, document every damaged area with photos and measurements, attend the adjuster meeting to point out damage and answer technical questions, provide accurate repair estimates, and ensure nothing is missed. This helps homeowners present complete, accurate information to their insurance company. Free damage inspections for Round Rock, Austin, Georgetown, and all Central Texas after major storms.',
    icon: 'ðŸ“‹',
    image: '/images/services/insurance-documentation.jpg',
    process: [
      { step: 1, title: 'Free Professional Roof Inspection', description: 'After a storm, we conduct a comprehensive roof inspection at no cost. We check for hail impacts, wind damage, missing shingles, damaged flashing, gutter damage, and hidden issues. We document everything with photos, measurements, and detailed notes. This inspection helps you understand what damage exists before calling your insurance company.' },
      { step: 2, title: 'Detailed Damage Documentation', description: 'We create a professional damage report with high-resolution photos of every damaged area, measurements and counts (number of hail strikes per square, damaged shingles, etc.), detailed written descriptions of all damage found, and our recommended scope of repair work. This report is YOURSâ€”you can share it with your insurance company to support your claim.' },
      { step: 3, title: 'Adjuster Meeting Support', description: 'When your insurance adjuster schedules their inspection, we meet them on-site at your request. We walk the roof with the adjuster, point out all damaged areas we documented, answer technical roofing questions they have, explain proper repair methods, and ensure all damage is properly noted. The adjuster makes all claim decisionsâ€”we simply provide roofing expertise to ensure accurate assessment.' },
      { step: 4, title: 'Accurate Repair Estimates', description: 'We provide detailed, accurate estimates for proper roof repairs using current market pricing and manufacturer-approved materials. This helps you and your adjuster understand the true cost of quality repairs. Your insurance company determines claim coverageâ€”we ensure the estimate reflects proper repair work to manufacturer warranty standards.' },
      { step: 5, title: 'Transparent Communication', description: 'Throughout the process, we keep you informed about what we found, what the adjuster noted, and what proper repairs will involve. If your claim is approved, we can perform the work. If your claim is denied or you choose not to file, there\'s no obligation. We answer your roofing questions and provide honest adviceâ€”you make all claim decisions.' },
    ],
    benefits: [
      'FREE professional roof damage inspection',
      'Detailed documentation with photos & measurements',
      'No-cost damage reports for your records',
      'Expert support during adjuster site visits',
      'Ensure all damage is properly identified',
      'Accurate repair estimatesâ€”manufacturer standards',
      'Work cooperatively with your adjuster',
      'Answer technical roofing questions',
      'YOU control your claimâ€”we provide expertise',
      'No pressureâ€”damage inspection is always free',
      'Serving Round Rock, Austin, Georgetown, Central Texas',
      'Available after major stormsâ€”quick response',
    ],
  },
  {
    id: '10',
    title: 'Roof Maintenance Plans',
    slug: 'roof-maintenance',
    shortDescription: 'Preventative maintenance programs to extend your roof\'s lifespan, catch problems early, and avoid costly emergency repairs.',
    description: 'Regular roof maintenance is like changing your car\'s oilâ€”it prevents expensive problems and extends the life of your investment. Our comprehensive maintenance plans include bi-annual professional inspections, seasonal cleaning and debris removal, minor repairs before they become major issues, and detailed photo reports after every visit. We catch small problems like loose shingles, damaged flashing, or clogged gutters before they cause leaks and interior damage. Most homeowners save 3-5 times their maintenance cost by avoiding emergency repairs and premature roof replacement. Our plans keep your manufacturer warranty valid (many require regular inspections), give you priority scheduling for repairs, and provide peace of mind that your roof is professionally monitored year-round. Perfect for homeowners who want to protect their investment, maintain their warranty, and avoid surprise roofing emergencies. Available in Round Rock, Austin, Georgetown, and throughout Central Texas with flexible scheduling.',
    icon: 'ðŸ”§',
    image: '/images/services/maintenance.jpg',
    process: [
      { step: 1, title: 'Initial Comprehensive Inspection', description: 'We start with a thorough baseline inspection of your entire roofing system. We check all shingles for damage or deterioration, inspect flashing around chimneys and vents, examine gutters and downspouts, look for signs of moisture or leaks, check attic ventilation, document current condition with photos, and create your roof\'s maintenance file. This establishes the starting point for ongoing monitoring.' },
      { step: 2, title: 'Customized Maintenance Schedule', description: 'Based on your roof\'s age, material, and condition, we create a personalized maintenance schedule. Newer roofs (0-10 years) typically need annual inspections, mid-life roofs (10-15 years) benefit from bi-annual visits, and older roofs (15+ years) may need quarterly monitoring. We schedule visits during spring (after storm season) and fall (before winter) for optimal timing.' },
      { step: 3, title: 'Seasonal Maintenance Visits', description: 'During each scheduled visit, we perform comprehensive maintenance: clean gutters and downspouts, remove debris from roof surface, check and reseal exposed nail heads, secure loose shingles, inspect and repair caulking around flashing, check ventilation system, look for signs of pest damage or moss/algae growth, and identify any developing issues. Each visit includes detailed photo documentation.' },
      { step: 4, title: 'Detailed Reporting & Recommendations', description: 'After every maintenance visit, you receive a comprehensive report with photos of current roof condition, list of maintenance performed, any issues discovered (with severity ratings), recommendations for repairs if needed, estimated timeline for addressing issues, and comparison to previous inspections showing changes over time. You\'ll always know exactly what\'s happening with your roof.' },
      { step: 5, title: 'Priority Repair Service', description: 'If our inspection reveals repairs needed, you get priority scheduling, discounted labor rates (10-20% off standard pricing), and transparent recommendationsâ€”we never upsell unnecessary work. Minor issues (loose shingles, small flashing repairs) are often fixed during the maintenance visit at no additional cost. Larger repairs are quoted clearly with options and timelines.' },
    ],
    benefits: [
      'Extend roof lifespan 5-10 years with regular care',
      'Save 3-5X maintenance cost by preventing major repairs',
      'Catch problems early when fixes are cheap',
      'Keep manufacturer warranty valid (inspection requirement)',
      'Bi-annual or custom inspection schedules',
      'Detailed photo reports after every visit',
      'Priority scheduling for repairs',
      '10-20% discount on repair labor',
      'Minor fixes included during visits',
      'Professional gutter cleaning included',
      'Ventilation and attic moisture monitoring',
      'Peace of mindâ€”roof professionally monitored',
    ],
  },
  {
    id: '11',
    title: 'Siding Installation & Repair',
    slug: 'siding-installation',
    shortDescription: 'Complete siding services including installation, repair, and replacement for fiber cement, vinyl, and wood siding systems.',
    description: 'Your home\'s siding is the first line of defense against Texas weatherâ€”protecting your structure from rain, wind, heat, and hail. We install and repair all major siding types including James Hardie fiber cement (the gold standard for durability), vinyl siding (low maintenance and affordable), wood siding (classic beauty), and composite materials. Whether you need storm damage repairs, full siding replacement, or new construction installation, we deliver professional craftsmanship with manufacturer-certified techniques. Damaged siding isn\'t just an eyesoreâ€”it can lead to water infiltration, mold growth, structural damage, and massive repair bills. We inspect for hidden damage, address moisture issues, replace rotted sections, and ensure proper installation with weather-resistant barriers and flashing. Most insurance policies cover storm-damaged siding (hail, wind, fallen trees). We provide detailed documentation to support your claim and work directly with adjusters. Serving Round Rock, Austin, Georgetown, and Central Texas with complete siding solutions that protect your home and enhance curb appeal.',
    icon: 'ðŸ ',
    image: '/images/services/siding.jpg',
    process: [
      { step: 1, title: 'Comprehensive Siding Assessment', description: 'We inspect your entire exterior to assess siding conditionâ€”checking for storm damage (hail dents, cracks, holes), moisture intrusion and rot, loose or missing panels, faded or damaged areas, and structural issues behind siding. We use moisture meters to detect hidden water damage and thermal imaging for insulation problems. You receive a detailed report with photos and recommendations.' },
      { step: 2, title: 'Material Selection & Customization', description: 'We help you choose the best siding for your home and budget. Options include: James Hardie fiber cement (30-50 year lifespan, fire-resistant, hail-resistant, best ROI), vinyl siding (20-40 years, low maintenance, widest color selection), wood siding (cedar, redwoodâ€”classic look), and engineered wood composites. We match existing siding perfectly for repairs or help you select new colors and styles for full replacement.' },
      { step: 3, title: 'Professional Installation', description: 'Our certified installers follow manufacturer specifications preciselyâ€”proper substrate preparation and moisture barriers, correct nailing patterns and spacing (critical for warranty), weather-resistant flashing around windows and doors, proper ventilation behind siding, seamless integration with trim and corners, and attention to expansion/contraction allowances. Done right, siding installation prevents future water damage and structural issues.' },
      { step: 4, title: 'Storm Damage Repairs & Insurance Claims', description: 'After hail or wind storms, we document all siding damage with photos and measurements, provide detailed estimates for insurance claims, meet with adjusters to ensure proper scope, and replace damaged sections while matching existing siding color and texture. Most insurance claims cover 100% of siding replacement minus your deductible when damage is storm-related. We handle the documentation.' },
      { step: 5, title: 'Quality Inspection & Warranty Protection', description: 'Before project completion, we conduct final quality inspectionâ€”verify proper installation per manufacturer specs, check all seams and transitions, ensure proper caulking and flashing, test for moisture infiltration, clean up all debris, and activate manufacturer warranty (typically 30-50 years for materials plus our workmanship warranty). Your home is protected and beautiful.' },
    ],
    benefits: [
      'All major siding typesâ€”fiber cement, vinyl, wood',
      'James Hardie certified installers',
      'Storm damage repair & insurance documentation',
      'Color matching for seamless repairs',
      'Moisture barrier & proper flashing installation',
      'Hail and wind damage expertise',
      '30-50 year manufacturer warranties',
      'Increase home value and curb appeal',
      'Energy efficiency improvements',
      'Complete trim and soffit services',
      'Work with insurance adjusters',
      'Free estimatesâ€”same-day available',
    ],
  },
  {
    id: '12',
    title: 'Attic Ventilation & Insulation',
    slug: 'attic-ventilation',
    shortDescription: 'Professional attic ventilation and insulation services to reduce energy costs, prevent roof damage, and improve home comfort.',
    description: 'Your attic is critical to your roof\'s health and your home\'s energy efficiency. In Texas, attics can reach 150-160Â°F in summerâ€”that extreme heat radiates into your living space, overworks your AC, and dramatically shortens your roof\'s lifespan by baking shingles from below. Proper attic ventilation and insulation solve this problem. We install ridge vents, soffit vents, powered attic fans, and other ventilation systems that create continuous airflow, removing hot air in summer and moisture in winter. Combined with proper insulation (spray foam, blown-in cellulose, or fiberglass batts), you can reduce cooling costs by 15-30%, extend your roof\'s life by 5-10 years, prevent ice dams and moisture damage, eliminate hot/cold rooms, and improve overall home comfort. Most homeowners see ROI within 3-5 years through energy savings alone. We conduct thermal imaging inspections to identify hot spots and inadequate insulation, recommend optimal ventilation ratios (1 sq ft per 150 sq ft of attic space), and install solutions that meet or exceed building codes. Serving Round Rock, Austin, Georgetown, and Central Texas with attic solutions that protect your roof and cut energy bills.',
    icon: 'ðŸŒ¬ï¸',
    image: '/images/services/ventilation.jpg',
    process: [
      { step: 1, title: 'Attic Inspection & Thermal Analysis', description: 'We conduct a comprehensive attic assessment using thermal imaging to identify hot spots, inadequate insulation areas, and ventilation problems. We measure current insulation R-value, check for moisture or mold issues, calculate ventilation ratios (intake vs exhaust), inspect existing vents for blockages, look for air leaks and gaps, and document attic temperature differentials. You receive a detailed report showing problem areas and improvement opportunities.' },
      { step: 2, title: 'Ventilation System Design', description: 'Based on your attic\'s square footage and roof design, we calculate optimal ventilation requirements (building code requires 1 sq ft vent per 150 sq ft attic space). We design a balanced system with proper intake vents (soffit vents, continuous soffit systems) and exhaust vents (ridge vents, box vents, turbine vents, or powered fans). Balanced airflow is criticalâ€”too much exhaust without intake causes backdrafting and reduces efficiency.' },
      { step: 3, title: 'Insulation Assessment & Recommendations', description: 'Texas building code requires R-30 to R-38 attic insulation. Most homes have R-19 or lessâ€”you\'re losing money every month. We measure current R-values, recommend upgrades (blown-in cellulose R-38-R-49, spray foam for air sealing, batt insulation for specific areas), calculate energy savings and ROI, and identify rebates and tax credits available. Proper insulation works WITH ventilation to maximize efficiency.' },
      { step: 4, title: 'Professional Installation', description: 'Our certified installers execute your attic improvement plan: install ridge vents along roof peak for continuous exhaust, add or upgrade soffit vents for intake airflow, install baffles to prevent insulation from blocking vents, blow in cellulose or fiberglass insulation to specified R-value, install powered attic fans if needed (with thermostats), air seal penetrations (pipes, wires, light fixtures), and create proper pathways for HVAC systems. Everything is done to building code and manufacturer specs.' },
      { step: 5, title: 'Performance Verification & Energy Savings', description: 'After installation, we verify proper airflow throughout attic space, confirm insulation depth and R-value achieved, check that all vents are unobstructed and functional, measure temperature differentials (should be within 10-15Â°F of outside temp), and provide before/after thermal images showing improvements. Most homeowners notice immediate comfort improvements and see 15-30% reduction in cooling costs the first summer.' },
    ],
    benefits: [
      'Reduce cooling costs 15-30% in Texas heat',
      'Extend roof lifespan 5-10 years',
      'Eliminate hot/cold rooms in home',
      'Prevent ice dams and moisture damage',
      'Professional thermal imaging inspection',
      'Ridge vents, soffit vents, powered fans',
      'Blown-in insulation up to R-49',
      'Air sealing for maximum efficiency',
      '3-5 year ROI through energy savings',
      'Increase home resale value',
      'Rebates and tax credits available',
      'Building code compliantâ€”guaranteed',
    ],
  },
  {
    id: '13',
    title: 'Pergola Construction',
    slug: 'pergolas',
    shortDescription: 'Custom pergola design and construction to enhance your outdoor living space with shade, style, and increased property value.',
    description: 'Transform your backyard into an outdoor oasis with a custom-built pergola. At Ripple Roofing & Construction, we design and build beautiful, durable pergolas that provide shade, define outdoor living areas, support climbing plants, and dramatically increase your home\'s value and curb appeal. Whether you envision a cozy patio retreat, an elegant entertaining space, or a stunning poolside structure, our craftsmanship delivers. We work with premium materials including pressure-treated lumber, cedar, composite materials, and aluminumâ€”each selected for Central Texas\'s challenging climate (intense sun, high humidity, occasional storms). Every pergola is custom-designed to your specifications: size, style (traditional, modern, rustic, contemporary), roof style (open lattice, louvered, solid), and integrated features (lighting, fans, privacy screens, built-in seating). Serving Round Rock, Austin, Georgetown, and throughout Central Texas, we handle design, permits, foundation work, construction, and finishing. Most projects completed in 3-5 days. Includes detailed 3D design mockups so you see exactly what you\'re getting before we build.',
    icon: 'ðŸŒ¿',
    image: '/images/services/pergola-1.jpg',
    process: [
      { step: 1, title: 'Free Consultation & Site Assessment', description: 'We visit your property to understand your vision, assess the installation site, evaluate sunlight patterns and wind exposure, discuss how you\'ll use the space (dining, lounging, entertaining, gardening), review existing landscaping and structures, and take measurements and photos. We help you determine optimal size, location, and orientation for your pergola. Free consultation includes design ideas and preliminary budget discussion.' },
      { step: 2, title: 'Custom Design & 3D Visualization', description: 'Our design team creates a custom pergola plan tailored to your home\'s architecture and your lifestyle. You receive 3D renderings showing exactly what your pergola will look like from multiple angles, detailed floor plans with dimensions, material selections and color options, integrated feature options (lighting, fans, privacy screens, planters), and transparent itemized pricing. We refine the design until it\'s perfectâ€”you approve before we build anything.' },
      { step: 3, title: 'Permits & HOA Approvals', description: 'We handle all permits required by your city (Round Rock, Austin, Georgetown, etc.) and coordinate HOA approvals if needed. Many Texas cities require permits for structures over 200 sq ft or attached to homes. We ensure your pergola meets all building codes for wind load, foundation requirements, and setback regulations. You don\'t deal with any red tapeâ€”we manage the entire approval process.' },
      { step: 4, title: 'Foundation & Structural Installation', description: 'We begin with proper foundation workâ€”concrete footings below frost line (12-18 inches in Central Texas), pier and beam or slab mounting depending on design, or deck attachment with structural bolts if adding to existing deck. Then we install structural posts (typically 6x6 or larger), horizontal beams and cross rafters, all hardware concealed or decorative, and proper bracing for Texas wind loads. Every connection is engineered for strength and longevity.' },
      { step: 5, title: 'Finishing Touches & Custom Features', description: 'We complete your pergola with finishing details that make it extraordinary: staining or painting (if wood) with UV-resistant finishes, integrated LED lighting for ambiance and functionality, ceiling fans with remote controls, retractable shade systems or fabric canopies, privacy screens or lattice panels, built-in seating or planters, and decorative hardware and accents. Most projects completed in 3-5 days with thorough cleanup daily.' },
      { step: 6, title: 'Final Walkthrough & Care Instructions', description: 'We conduct a comprehensive walkthrough of your completed pergola, explain all features and controls (fans, lights, retractable shades), provide maintenance instructions for your specific materials, give you warranty documentation (5-year workmanship warranty), schedule follow-up inspection after 30 days, and ensure you\'re 100% thrilled with your new outdoor space. Your backyard is now an extension of your home!' },
    ],
    benefits: [
      'Custom designâ€”perfectly tailored to your space',
      '3D renderings before construction begins',
      'Premium materials: cedar, composite, aluminum',
      'Integrated lighting & ceiling fans available',
      'Retractable shade systems for flexibility',
      'Privacy screens & built-in features',
      'Engineered for Texas wind & weather',
      'Increase home value 5-15%',
      'Permits & HOA approvals handled for you',
      'Most projects completed in 3-5 days',
      '5-year workmanship warranty',
      'Free consultation & design mockups',
    ],
  },
  {
    id: '14',
    title: 'Paintless Dent Repair (PDR)',
    slug: 'paintless-dent-repair',
    shortDescription: 'Professional paintless dent repair for hail damageâ€”restore your vehicle without repainting. Powered by Paintless Perfection.',
    description: 'Hail storms in Central Texas can devastate vehicles. Paintless Dent Repair (PDR) is the gold-standard solution for removing hail dents, door dings, and minor body damage without affecting your vehicle\'s original paint or factory finish. Our PDR specialists at Paintless Perfection use precision tools and expert techniques to massage dents out from behind panels, preserving your car\'s value and eliminating the need for expensive body shop work. PDR is faster (same-day service often available), more affordable (typically 50-70% less than traditional repair), and maintains your vehicle\'s factory paint (no color matching issues or diminished resale value). Perfect for hail damage (dozens to hundreds of dents), door dings and parking lot damage, minor collision dents, and creases from shopping carts or sports equipment. We work directly with insurance companies, provide mobile service (we come to you in Round Rock, Austin, Georgetown, Central Texas), and offer free estimates. Most insurance policies cover hail damage PDR with minimal out-of-pocket cost. Get your vehicle looking new againâ€”often in just a few hours!',
    icon: 'ðŸš—',
    image: '/images/services/pdr.jpg',
    process: [
      { step: 1, title: 'Free Damage Assessment & Estimate', description: 'We inspect your vehicle to assess all dent damageâ€”counting individual dents (hail storms can cause 50-200+ dents), measuring dent depth and size, checking paint condition (PDR requires intact paint), identifying any dents too severe for PDR (we\'ll tell you honestly), and documenting damage with photos for insurance. You receive a detailed written estimate within 15 minutes. Free assessments at our shop or your location (mobile service available).' },
      { step: 2, title: 'Insurance Coordination (If Applicable)', description: 'We work with ALL insurance companiesâ€”State Farm, USAA, Progressive, Geico, Allstate, and more. We help you file your claim, provide professional damage documentation, meet with insurance adjusters, and ensure proper repair scope is approved. We handle the insurance paperworkâ€”you just approve the repairs.' },
      { step: 3, title: 'Precision Paintless Dent Removal', description: 'Our master PDR technicians access dents from behind the panel using specialized tools. We carefully massage the metal back to its original shape, working each dent from the inside out, using precision lighting to ensure perfect results, preserving your factory paint and finish, requiring no sanding, filling, or repainting, and maintaining your vehicle\'s original value. The process is meticulousâ€”larger hail jobs can take 1-3 days depending on 1-3 days depending on dent count.' },
      { step: 4, title: 'Quality Inspection & Warranty', description: 'Before delivery, we inspect every repaired area under specialized lighting to ensure 100% quality. We provide a lifetime warranty on all PDR workâ€”if a repaired dent returns (extremely rare), we fix it free. You also receive before/after photos showing the transformation, detailed invoice for insurance/records, and care instructions (none neededâ€”PDR is permanent!). Your vehicle looks factory-new again.' },
      { step: 5, title: 'Mobile Service Available', description: 'For your convenience, we offer mobile PDR service throughout Round Rock, Austin, Georgetown, and Central Texas. We come to your home, office, or anywhere you need. Mobile service includes all the same quality and warranty as in-shop repairs. Perfect for busy schedules or if you have multiple vehicles needing PDR. Schedule online or call for mobile availability.' },
    ],
    benefits: [
      'Remove hail dents without repainting',
      'Preserves factory paint & vehicle value',
      '50-70% less expensive than body shops',
      'Same-day service often available',
      'Works with ALL insurance companies',
      'Mobile serviceâ€”we come to you',
      'Free estimates & insurance documentation',
      'Lifetime warranty on all PDR repairs',
      'Master PDR techniciansâ€”20+ years experience',
      'No diminished value from repainting',
      'Environmentally friendlyâ€”no paint/chemicals',
      'Powered by Paintless Perfection',
    ],
  },
  {
    id: '15',
    title: 'Stone-Coated Steel Roofing',
    slug: 'stone-coated-steel-roofing',
    shortDescription: 'Premium stone-coated steel roofingâ€”the ultimate combination of metal durability and architectural beauty with 50+ year lifespan.',
    description: 'Stone-coated steel roofing represents the pinnacle of residential roofing technologyâ€”combining the legendary durability of metal with the classic beauty of traditional shingles or tile. These premium roofing systems feature steel panels coated with stone granules, delivering unmatched performance in Central Texas\'s challenging climate. With a 50+ year lifespan (2-3 times longer than asphalt shingles), Class 4 hail impact resistance, 120+ mph wind ratings, energy-efficient reflective surfaces, and fire-resistant construction (Class A rating), stone-coated steel is the investment-grade choice for discerning homeowners. Perfect for luxury neighborhoods in Round Rock, Georgetown, Leander, and Austin where HOA architectural standards demand both beauty and performance. While the initial investment is higher ($18,000-$35,000+ depending on home size), the lifetime value is extraordinaryâ€”you\'ll never need another roof replacement. We\'re certified installers of premium stone-coated steel systems, providing expert installation with comprehensive warranties that protect your investment for decades.',
    icon: 'ðŸ”ï¸',
    image: '/images/services/stone-coated-steel.jpg',
    process: [
      { step: 1, title: 'Comprehensive Home Assessment', description: 'We begin with a thorough evaluation of your home and roofing needs. Our team inspects your current roof structure and condition, assesses roof pitch and complexity (stone-coated steel works on slopes 2:12 to 12:12), evaluates your home\'s architectural style for best profile match, discusses your long-term plans (planning to stay 15+ years makes this investment ideal), reviews your neighborhood\'s HOA requirements and architectural guidelines, and provides honest guidance on whether stone-coated steel is right for your specific situation. Free consultation with no pressureâ€”we help you make the best decision.' },
      { step: 2, title: 'Material Selection & Customization', description: 'Stone-coated steel offers remarkable versatility. You\'ll choose from multiple profile styles: shake/shingle profiles (mimic cedar shake or architectural shingles), tile profiles (Spanish, Mediterranean, barrel tile looks), and specialty profiles (slate, wood shake, designer styles). Select from 15+ colors with stone granule finishes that never fade. We show you samples, discuss energy efficiency ratings (cool roof colors reduce attic heat), explain warranty differences between manufacturers, review weight considerations (stone-coated steel is heavier than shingles but lighter than concrete tile), and help you navigate HOA approval process with documentation and samples.' },
      { step: 3, title: 'Detailed Proposal & Investment Analysis', description: 'You receive a comprehensive written proposal showing itemized costs for materials, labor, underlayment, flashing, ventilation upgrades, and disposal. We provide lifetime cost comparison vs. asphalt shingles (you\'ll replace asphalt 2-3 times in 50 years), insurance savings potential (many insurers offer 10-35% discounts for impact-resistant roofing), resale value increase (premium roofing adds $15,000-$40,000 to home value), energy savings from reflective surfaces (10-25% cooling cost reduction), and total cost of ownership analysis. We also discuss financing options to make the investment manageable. Our goal is complete transparencyâ€”you understand exactly what you\'re getting.' },
      { step: 4, title: 'Expert Installation to Manufacturer Specs', description: 'Stone-coated steel installation requires specialized expertiseâ€”improper installation voids warranties. Our certified installers follow rigorous manufacturer protocols: remove existing roofing down to roof decking, inspect and repair decking as needed (stone-coated steel requires solid substrate), install high-performance underlayment (synthetic or premium felt), create proper ventilation (ridge vents, soffit vents for continuous airflow), install panels with precise overlap and fastening patterns, seal all penetrations and flashing points with premium materials, integrate valleys and transitions seamlessly, and ensure proper drainage and water management. Typical installation takes 3-5 days depending on roof size and complexity.' },
      { step: 5, title: 'Quality Assurance & Warranty Activation', description: 'Before project completion, we conduct comprehensive final inspection verifying every panel is properly fastened and aligned, all flashing and trim work meets specifications, ventilation system functions correctly, and no debris or materials remain. We perform water testing on valleys and penetrations if needed. You receive complete warranty documentation including 50-year manufacturer material warranty, 30-year finish/color warranty (stone granules won\'t fade), our 10-year workmanship warranty, and all installation photos for your permanent records. We also provide maintenance guidelines (minimal maintenance required) and schedule 1-year follow-up inspection. Your roof is now protected for half a century!' },
    ],
    benefits: [
      '50+ year lifespanâ€”2-3X longer than asphalt shingles',
      'Class 4 hail impact ratingâ€”highest available',
      '120+ mph wind resistanceâ€”hurricane-grade',
      'Class A fire resistanceâ€”non-combustible metal core',
      'Energy efficientâ€”reduces cooling costs 10-25%',
      'Beautiful profilesâ€”shake, tile, shingle, slate styles',
      '15+ colors with stone granule finish',
      'Never needs replacementâ€”lifetime roofing solution',
      'Increases home value $15,000-$40,000+',
      'Insurance discountsâ€”many insurers offer 10-35% savings',
      'HOA approvedâ€”meets architectural requirements',
      'Environmentally friendlyâ€”100% recyclable metal',
      'Warranty: 50-year materials + 30-year finish + 10-year workmanship',
      'Perfect for luxury neighborhoods in Central Texas',
      'Certified professional installation',
      'Financing available for qualified homeowners',
    ],
  },
]

// Service Types for Form
export const SERVICE_TYPES = [
  'Roof Repair',
  'Roof Replacement',
  'New Installation',
  'Storm Damage',
  'Other',
] as const

// Trust Bar / Value Propositions
export const VALUE_PROPS = [
  {
    icon: 'âœ“',
    title: 'CertainTeed Shingle Master',
    description: 'Certified Excellence',
  },
  {
    icon: 'ï¿½ï¸',
    title: 'Fully Insured',
    description: 'Your protection guaranteed',
  },
  {
    icon: 'ðŸš¨',
    title: '24/7 Emergency Service',
    description: 'Always here when you need us',
  },
  {
    icon: 'ðŸŒŸ',
    title: 'Central Texas Experts',
    description: 'Serving the Austin Metro',
  },
]

// Project Categories
export const PROJECT_CATEGORIES = [
  'All',
  'Commercial',
  'Residential',
  'Metal',
  'Shingle',
  'Tile',
] as const
