import type { NavLink, Service } from '@/types'

// Site Configuration
export const SITE_CONFIG = {
  name: 'Ripple Roofing & Construction',
  description: 'Premium Roofing Services in Central Texas',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',
  phone: '(512) 763-5277',
  phoneRaw: '5127635277',
  email: 'info@rippleroofs.com',
  address: '1000 Heritage Center Circle, Round Rock, TX 78664',
  city: 'Round Rock',
  state: 'Texas',
  zip: '78664',
  hours: '24/7 Emergency Service Available',
  serviceArea: 'Central Texas, Austin Metro, San Antonio, Georgetown, Round Rock, Killeen, Copperas Cove, Portland',
  certifications: ['CertainTeed Shingle Master', 'Fully Insured'],
  social: {
    facebook: 'https://facebook.com/rippleroofs',
    instagram: '',
    linkedin: '',
    twitter: '',
    youtube: '',
  },
}

// Navigation Links
export const NAV_LINKS: NavLink[] = [
  { href: '/', label: 'Home' },
  { 
    href: '/services', 
    label: 'Services',
    children: [
      { href: '/services/residential-roofing', label: 'Residential Roofing' },
      { href: '/services/commercial-roofing', label: 'Commercial Roofing' },
      { href: '/services/roof-replacement', label: 'Roof Replacement' },
      { href: '/services/roof-repairs', label: 'Roof Repairs' },
      { href: '/services/emergency-services', label: 'Emergency Services' },
      { href: '/services/roof-inspection', label: 'Roof Inspection' },
      { href: '/services/gutter-installation', label: 'Gutter Installation' },
      { href: '/services/storm-damage-restoration', label: 'Storm Damage Restoration' },
      { href: '/services/insurance-claim-documentation', label: 'Insurance Claim Documentation' },
    ]
  },
  {
    href: '/locations',
    label: 'Locations',
    children: [
      { href: '/locations/round-rock', label: 'Round Rock' },
      { href: '/locations/austin', label: 'Austin' },
      { href: '/locations/pflugerville', label: 'Pflugerville' },
      { href: '/locations/cedar-park', label: 'Cedar Park' },
      { href: '/locations/leander', label: 'Leander' },
      { href: '/locations/georgetown', label: 'Georgetown' },
      { href: '/locations/san-marcos', label: 'San Marcos' },
      { href: '/locations/new-braunfels', label: 'New Braunfels' },
      { href: '/locations/san-antonio', label: 'San Antonio' },
      { href: '/locations/temple', label: 'Temple' },
      { href: '/locations/killeen', label: 'Killeen' },
      { href: '/locations/copperas-cove', label: 'Copperas Cove' },
      { href: '/locations/waco', label: 'Waco' },
    ]
  },
  { href: '/projects', label: 'Projects' },
  { href: '/about', label: 'About' },
  { href: '/blog', label: 'Blog' },
  { href: '/financing', label: 'Financing' },
  { href: '/faq', label: 'FAQ' },
  { href: '/contact', label: 'Contact' },
]

// Services Data
export const SERVICES: Service[] = [
  {
    id: '1',
    title: 'Residential Roofing',
    slug: 'residential-roofing',
    shortDescription: 'Complete residential roofing services—installation, repair, replacement, and maintenance for Central Texas homes.',
    description: 'Your home is your family\'s sanctuary and your largest investment. Ripple Roofing & Construction provides comprehensive residential roofing services for homeowners throughout Central Texas—from simple repairs to complete roof replacements. As CertainTeed Shingle Master certified contractors, we offer expert installation of all roofing types: architectural shingles, impact-resistant shingles, metal roofing, tile, and specialty materials. We serve Round Rock, Austin, Georgetown, and surrounding communities with honest assessments, quality craftsmanship, and warranties that protect your investment. Whether you need emergency storm repairs, routine maintenance, or a brand new roof, we treat your home like our own. Free inspections, transparent pricing, and 10-year workmanship warranty on all installations.',
    icon: '🏠',
    image: '/images/services/residential-roofing.jpg',
    process: [
      { step: 1, title: 'Free Roof Inspection & Assessment', description: 'We thoroughly inspect your roof\'s condition, identify any issues, document with photos, and assess remaining lifespan. Whether you need minor repairs or full replacement, we provide honest recommendations. Free inspections after major storms!' },
      { step: 2, title: 'Detailed Consultation & Material Selection', description: 'We explain your options clearly—shingle types, metal roofing, tile, impact-resistant materials—with pros, cons, costs, and warranties. We help you choose materials that fit your home style, budget, and Central Texas climate needs.' },
      { step: 3, title: 'Transparent Written Estimate', description: 'You receive a detailed, itemized quote with no hidden fees or surprise charges. We explain every line item, timeline expectations, and warranty coverage. We help with insurance claims if storm damage is involved.' },
      { step: 4, title: 'Professional Installation', description: 'Our certified crews arrive on time with all materials and equipment. We protect your property, follow manufacturer specifications precisely, maintain a clean work site, and complete most projects in 1-3 days. Daily progress updates keep you informed.' },
      { step: 5, title: 'Quality Inspection & Warranty Activation', description: 'We conduct a final walkthrough with you, perform magnetic nail sweep, clean up completely, and activate your manufacturer material warranty plus our 10-year workmanship warranty. You get copies of all documentation for your records.' },
    ],
    benefits: [
      'CertainTeed Shingle Master Certified contractors',
      'All roofing types: shingles, metal, tile, specialty',
      'Free inspections—no obligation quotes',
      'Impact-resistant shingles for hail protection',
      'Insurance claim assistance and documentation',
      'Financing options available (various terms)',
      '10-year workmanship warranty on installations',
      'Manufacturer warranties: 25-50 year coverage',
      'Serving Central Texas: Round Rock, Austin, Georgetown',
      'Emergency storm repairs—24/7 availability',
      'Transparent pricing—no hidden fees',
      'Projects completed in 1-3 days typically',
    ],
  },
  {
    id: '2',
    title: 'Commercial Roofing',
    slug: 'commercial-roofing',
    shortDescription: 'Professional commercial roofing for businesses—flat roofing systems, TPO, EPDM, metal, and preventative maintenance plans.',
    description: 'Your commercial roof protects your business, inventory, equipment, and livelihood. Ripple Roofing & Construction provides comprehensive commercial roofing services for businesses throughout Central Texas—from flat roof installations to ongoing maintenance programs. We specialize in flat roofing systems (TPO, EPDM, modified bitumen), metal roofing, and commercial roof coatings. Whether you own retail space, office buildings, warehouses, apartment complexes, or industrial facilities in Round Rock, Austin, Georgetown, or surrounding areas, we minimize business disruption while delivering quality work. We work after-hours or weekends when needed, provide detailed warranties, and offer preventative maintenance plans that extend roof life and prevent costly emergency repairs. Fully licensed, insured, and experienced with all commercial roofing systems.',
    icon: '🏢',
    image: '/images/services/commercial-roofing.jpg',
    process: [
      { step: 1, title: 'Free Commercial Roof Assessment', description: 'We conduct a thorough inspection of your commercial roof, identify issues, assess remaining lifespan, document with photos/measurements, and provide written evaluation. We work around your business hours and provide detailed reports within 24-48 hours.' },
      { step: 2, title: 'Customized Solution & Proposal', description: 'We design a solution tailored to your property type, budget, and timeline. Options include full replacement, roof restoration/coating, or targeted repairs. Detailed written proposal with material specs, timeline, and transparent pricing. We explain ROI and financing options.' },
      { step: 3, title: 'Minimal-Disruption Installation', description: 'We schedule work to minimize impact on your operations—after hours, weekends, or phased approach. Professional crews arrive on time with all equipment. We protect your property, maintain safety protocols, and keep you updated daily on progress.' },
      { step: 4, title: 'Quality Assurance & Documentation', description: 'Final inspection ensures code compliance and quality standards. Complete cleanup, documentation photos, warranty registration, and maintenance recommendations. We provide copies of all permits, inspections, and warranty documents for your records.' },
      { step: 5, title: 'Preventative Maintenance Programs', description: 'Optional maintenance plans include bi-annual inspections, minor repairs, drainage cleaning, and detailed condition reports. Catch small issues before they become expensive emergencies. Extends roof life 5-10 years and maintains warranty validity.' },
    ],
    benefits: [
      'All flat roofing systems: TPO, EPDM, modified bitumen',
      'Metal roofing for commercial applications',
      'Roof coating and restoration services',
      'After-hours and weekend scheduling available',
      'Minimal business disruption guarantee',
      'Detailed proposals with transparent pricing',
      'Preventative maintenance programs',
      'Emergency repair response—24/7 availability',
      'Fully licensed and insured for commercial work',
      '10-year workmanship warranty',
      'Manufacturer warranties: 10-30 years',
      'Serving Central Texas businesses',
    ],
  },
  {
    id: '3',
    title: 'Roof Replacement',
    slug: 'roof-replacement',
    shortDescription: 'Expert roof replacement services in Central Texas. From material selection to installation, we guide you through every step with transparency and craftsmanship.',
    description: 'When it\'s time for a new roof, Ripple Roofing & Construction guides you through the process with expertise and transparency. As a CertainTeed Shingle Master certified contractor, we offer premium roofing materials specifically chosen for Central Texas\'s challenging climate—intense heat, severe storms, and hail. Whether your roof has reached the end of its lifespan, sustained storm damage, or you\'re upgrading for energy efficiency and curb appeal, we provide comprehensive roof replacement services with industry-leading warranties. Serving Round Rock, Austin, Georgetown, and all of Central Texas, we\'ve helped thousands of homeowners protect their most valuable investment with quality craftsmanship and honest service.',
    icon: '🔄',
    image: '/images/services/roof-replacement.jpg',
    process: [
      { step: 1, title: 'Free Comprehensive Inspection', description: 'We conduct a thorough 50-point inspection of your existing roof, identifying all issues, potential concerns, and underlying problems. We document everything with photos and provide a detailed written report.' },
      { step: 2, title: 'Material Selection & Consultation', description: 'We guide you through material options including architectural shingles, impact-resistant shingles, metal roofing, and tile. We explain pros/cons, costs, warranties, and what works best for your specific home, budget, and neighborhood.' },
      { step: 3, title: 'Detailed Written Estimate', description: 'You receive a transparent, itemized estimate with no hidden fees. We explain every line item, timeline expectations, and payment terms. We help you understand insurance coverage if applicable and financing options available.' },
      { step: 4, title: 'Project Preparation', description: 'We handle all permits and HOA approvals. We protect your property with tarps and barriers, coordinate material delivery, and provide a detailed project timeline. Your project manager will be your single point of contact throughout.' },
      { step: 5, title: 'Expert Installation', description: 'Our certified crews arrive on schedule and complete most replacements in 1-3 days. We use premium materials, follow manufacturer specifications precisely, and maintain a clean, safe work site. Daily progress updates keep you informed.' },
      { step: 6, title: 'Quality Inspection & Cleanup', description: 'We conduct a final walkthrough with you, ensuring complete satisfaction. Our magnetic sweep removes all nails and debris. We leave your property cleaner than we found it, with professional disposal of all materials.' },
      { step: 7, title: 'Warranty Activation & Follow-Up', description: 'We register your warranty with the manufacturer, provide all documentation, and schedule a follow-up inspection after your first rain. We\'re here for the life of your roof with ongoing support and maintenance.' },
    ],
    benefits: [
      'CertainTeed Shingle Master Certified—elite contractor status with enhanced warranties',
      'Premium materials rated for Texas heat, hail, and high winds',
      'Transparent pricing with detailed, itemized estimates',
      'Most projects completed in 1-3 days with minimal disruption',
      'Comprehensive warranties on both materials (25-50+ years) and workmanship (10 years)',
      'Insurance claim assistance including adjuster meetings and documentation',
      'Flexible financing options with approved credit',
      'Thorough cleanup including magnetic nail sweep',
      'Local Central Texas company—not storm chasers, here for the long term',
      'A+ BBB rating with hundreds of satisfied customers',
      'Free inspections after severe weather events',
      '24/7 emergency service availability',
    ],
  },
  {
    id: '4',
    title: 'Roof Repairs',
    slug: 'roof-repairs',
    shortDescription: 'Fast, reliable roof repairs that stop leaks and prevent costly damage.',
    description: 'Don\'t let a small roof problem become a big expense. Our expert roof repair services in Round Rock, Austin, and Georgetown address everything from minor leaks and missing shingles to storm damage and flashing issues. As a CertainTeed Shingle Master certified contractor, we use premium materials and proven techniques to restore your roof\'s integrity. Most repairs are completed in just a few hours, with same-day service available. We provide honest assessments—if repair isn\'t the best option, we\'ll tell you. Our 10-year workmanship warranty backs every repair we make.',
    icon: '🔧',
    image: '/images/services/roof-repairs.jpg',
    process: [
      { step: 1, title: 'Free Inspection & Diagnosis', description: 'Thorough evaluation to identify all issues, not just visible damage. We check for underlying problems that could worsen. Honest assessment of whether repair or replacement is more cost-effective.' },
      { step: 2, title: 'Detailed Photo Documentation', description: 'We document all damage with photos and notes for your records and insurance claims. Clear explanation of what needs fixing and why.' },
      { step: 3, title: 'Transparent Pricing', description: 'Upfront pricing with no surprises. Itemized quote showing materials and labor. We work directly with insurance companies if storm damage is involved.' },
      { step: 4, title: 'Professional Repair', description: 'Experienced crews complete most repairs in 2-4 hours. We match existing materials for seamless appearance. All work meets manufacturer specifications and local building codes.' },
      { step: 5, title: 'Quality Inspection', description: 'Final walkthrough to ensure repair quality. We test for leaks and verify structural integrity. Magnetic nail sweep of work area.' },
      { step: 6, title: '10-Year Workmanship Warranty', description: 'Every repair backed by our comprehensive workmanship warranty. If the repaired area has issues, we fix it at no charge.' },
    ],
    benefits: [
      'Same-day and emergency repair services available',
      'CertainTeed Shingle Master certified technicians',
      'Premium Texas-rated materials that match existing roof',
      'Complete in 2-4 hours for most repairs',
      '10-year workmanship warranty on all repairs',
      'Insurance claim assistance and documentation',
      'Honest assessments—we\'ll tell you if replacement is better',
      'No hidden fees or surprise charges',
      'Free inspections after major storms',
      'Local company serving Central Texas since [year]',
      'A+ BBB rating with hundreds of satisfied customers',
      '24/7 emergency service for urgent situations',
    ],
  },
  {
    id: '5',
    title: 'Emergency Services',
    slug: 'emergency-services',
    shortDescription: '24/7 emergency roofing response—we\'re there when you need us most.',
    description: 'Roof emergencies don\'t wait for business hours. When storms hit, trees fall, or sudden leaks threaten your home, we respond immediately—24 hours a day, 7 days a week, 365 days a year. Our emergency roofing services serve Round Rock, Austin, Georgetown, and all Central Texas with rapid response times (typically 2-4 hours). We provide emergency tarping to stop water intrusion, assess damage for insurance claims, and coordinate permanent repairs. Whether it\'s 2 PM or 2 AM, our certified crews are ready to protect your home and minimize damage. Call (512) 763-5277 anytime for immediate emergency assistance.',
    icon: '🚨',
    image: '/images/services/emergency-services.jpg',
    process: [
      { step: 1, title: '24/7 Emergency Call & Dispatch', description: 'Call (512) 763-5277 anytime. We answer immediately—no voicemail, no waiting. Our dispatcher gathers essential information and sends the nearest crew. Average response time: 2-4 hours depending on location and weather conditions.' },
      { step: 2, title: 'Immediate Emergency Tarping', description: 'Our crew arrives with heavy-duty tarps, securing materials, and safety equipment. We quickly cover damaged areas to stop water intrusion and prevent further damage to your home, belongings, and structure. Your home is protected within 30-60 minutes of arrival.' },
      { step: 3, title: 'Damage Assessment & Documentation', description: 'Once your home is secure, we conduct a thorough assessment of all damage. We document everything with photos for insurance claims, identify safety hazards, and determine the scope of permanent repairs needed.' },
      { step: 4, title: 'Insurance Coordination', description: 'We help you contact your insurance company, provide documentation they need, and schedule adjuster visits. Our reports are insurance-acceptable and comprehensive. We can attend adjuster meetings with you.' },
      { step: 5, title: 'Permanent Repair Plan', description: 'We provide a detailed estimate for permanent repairs, timeline expectations, and material options. No pressure—you decide when to proceed. Emergency tarping buys you time to make informed decisions.' },
      { step: 6, title: 'Complete Restoration', description: 'When you\'re ready, our certified crews complete all permanent repairs using premium materials. We restore your roof to full integrity, backed by our 10-year workmanship warranty.' },
    ],
    benefits: [
      '24/7/365 availability—we answer every call',
      'Rapid 2-4 hour response time in Central Texas',
      'Immediate emergency tarping to stop water damage',
      'Heavy-duty professional-grade tarps and securing',
      'Complete damage documentation for insurance',
      'Insurance claim assistance and adjuster coordination',
      'Safety hazard identification and mitigation',
      'Certified, experienced emergency response crews',
      'Transparent emergency service pricing',
      'Permanent repair coordination when you\'re ready',
      '10-year workmanship warranty on repairs',
      'Local company serving Round Rock, Austin, Georgetown',
    ],
  },
  {
    id: '6',
    title: 'Roof Inspection & Assessment',
    slug: 'roof-inspection',
    shortDescription: 'Comprehensive 50-point roof inspections with detailed photo reports.',
    description: 'Knowledge is power when it comes to your roof. Our comprehensive roof inspections provide you with a complete understanding of your roof\'s condition—whether you\'re buying a home, selling a property, concerned about storm damage, or simply want peace of mind. As CertainTeed Shingle Master certified contractors, we conduct thorough 50-point inspections of every roof component. You receive a detailed photo report with condition ratings, remaining lifespan estimates, and prioritized repair recommendations. We serve homeowners in Round Rock, Austin, Georgetown, and all Central Texas. Most inspections are completed in 45-60 minutes. Free inspections after major storms!',
    icon: '🔍',
    image: '/images/services/roof-inspection.jpg',
    process: [
      { step: 1, title: 'Schedule Your Inspection', description: 'Quick online booking or call (512) 763-5277. We offer flexible scheduling including evenings and weekends. Free inspections after major storms or for insurance claims.' },
      { step: 2, title: 'Comprehensive 50-Point Inspection', description: 'Our certified technician examines all roof components: shingles, flashing, valleys, penetrations, gutters, ventilation, underlayment visibility, structural integrity. We use drone photography for steep or complex roofs. Takes 45-60 minutes.' },
      { step: 3, title: 'Detailed Photo Report', description: 'You receive a comprehensive report with photos of every issue, condition ratings (1-10 scale), remaining lifespan estimates, and repair priority levels (immediate, near-term, monitor). Sent via email within 24 hours.' },
      { step: 4, title: 'Review & Consultation', description: 'We walk through findings with you in person or by phone. No pressure—just honest recommendations. If repairs are needed, we provide transparent pricing. If your roof is fine, we tell you that too!' },
      { step: 5, title: 'Optional Follow-Up', description: 'We can schedule repairs, provide quotes for replacement if needed, or simply schedule your next routine inspection. All findings documented for your records and future reference.' },
    ],
    benefits: [
      'Comprehensive 50-point inspection checklist',
      'Detailed photo report with condition ratings',
      'Certified CertainTeed Shingle Master inspectors',
      'Drone photography for steep/complex roofs',
      'Completed in 45-60 minutes',
      'Free post-storm inspections',
      'Insurance claim documentation assistance',
      'Pre-purchase home inspection reports',
      'Annual maintenance inspection programs',
      'Honest assessments—no pressure sales',
      'Remaining lifespan estimates for planning',
      '24-hour report turnaround',
    ],
  },
  {
    id: '7',
    title: 'Gutter Installation',
    slug: 'gutter-installation',
    shortDescription: 'Professional seamless gutter installation—5" and 6" systems that protect your foundation.',
    description: 'Your gutters are your home\'s first line of defense against water damage. Professional gutter installation protects your foundation, prevents basement flooding, eliminates soil erosion, and preserves your landscaping. We install seamless aluminum gutters custom-fabricated on-site to fit your home perfectly—no leaky seams every 10 feet like sectional gutters. Choose from 5-inch standard systems (most homes) or 6-inch high-capacity systems (large roofs, heavy rainfall areas). We serve Round Rock, Austin, Georgetown, and all Central Texas with 20+ color options to match any home. Our gutters come with a 20-year material warranty and 10-year workmanship warranty. Typical installation completed in 1 day!',
    icon: '💧',
    image: '/images/services/gutter-installation.jpg',
    process: [
      { step: 1, title: 'Free Assessment & Measurement', description: 'We measure your roofline, evaluate drainage needs, assess downspout placement for optimal water flow, check fascia condition, and identify problem areas. You choose gutter size (5" or 6"), color (20+ options), and optional gutter guards.' },
      { step: 2, title: 'Custom Fabrication On-Site', description: 'We bring our seamless gutter machine to your home and custom-fabricate gutters to your exact measurements. No seams except at corners—means no leaks! Available in .027 or .032 gauge aluminum (thicker = more durable).' },
      { step: 3, title: 'Professional Installation', description: 'We remove old gutters if needed (disposal included), repair fascia if damaged, install seamless gutters with hidden hangers every 24 inches, properly pitch gutters for drainage (1/4" per 10 feet), install downspouts with extensions, and seal all connections.' },
      { step: 4, title: 'Testing & Final Inspection', description: 'We run water through entire system to verify proper flow and drainage, check all connections for leaks, ensure downspouts direct water 4-6 feet from foundation, clean up all debris, and provide maintenance tips. Typically completed in 1 day!' },
      { step: 5, title: 'Warranty & Maintenance Options', description: '20-year material warranty on gutters, 10-year workmanship warranty on installation. Optional: gutter guard installation (keeps leaves out), annual cleaning service programs, and routine inspection packages.' },
    ],
    benefits: [
      'Seamless gutters—no leaky joints every 10 feet',
      'Custom-fabricated on-site for perfect fit',
      '5-inch or 6-inch systems available',
      '20+ color options to match your home',
      'Hidden hanger system—clean appearance',
      '.027 or .032 gauge aluminum (thicker options)',
      'Foundation protection prevents $10k-$50k repairs',
      'Prevents basement flooding and moisture',
      'Eliminates soil erosion around home',
      'Protects landscaping and flower beds',
      '20-year material + 10-year workmanship warranty',
      'Most homes completed in 1 day',
    ],
  },
  {
    id: '8',
    title: 'Storm Damage Restoration',
    slug: 'storm-damage-restoration',
    shortDescription: 'Expert storm damage assessment and restoration—we handle insurance claims, emergency repairs, and complete restoration.',
    description: 'Central Texas storms bring hail, high winds, fallen trees, and flying debris that can devastate your roof. Storm damage restoration requires specialized expertise—identifying hidden damage that untrained eyes miss, documenting everything for insurance claims, working with adjusters to maximize coverage, and executing repairs to full manufacturer warranty standards. We respond within 2 hours for emergency tarping and immediate protection, conduct comprehensive damage assessments using drones and thermal imaging, handle all insurance paperwork and adjuster meetings, and restore your roof to better-than-before condition. We serve Round Rock, Austin, Georgetown, and all Central Texas. Our storm specialists have documented over 2,000 insurance claims and recovered millions in rightful coverage for homeowners. Most insurance claims cover 100% of roof replacement minus deductible—we ensure you get what you deserve.',
    icon: '⛈️',
    image: '/images/services/storm-damage.jpg',
    process: [
      { step: 1, title: 'Emergency Response & Immediate Protection', description: 'We respond within 2 hours for emergency situations. Our crew performs emergency tarping to prevent interior water damage, documents all damage with photos and video, secures loose materials, identifies safety hazards, and provides immediate stability. Available 24/7 for storm emergencies.' },
      { step: 2, title: 'Comprehensive Damage Assessment', description: 'We conduct a thorough inspection using drones for aerial documentation, thermal imaging to detect hidden moisture, measure hail impacts and wind damage, check for structural issues, inspect gutters and flashing, document every detail for insurance, and create a complete scope of work with pricing.' },
      { step: 3, title: 'Insurance Claims Management', description: 'We handle the entire insurance process—file your claim, schedule adjuster meeting, meet adjuster on-site and advocate for full coverage, document all damage with professional reports, fight for proper scope if needed (supplements), negotiate fair settlements, and ensure you maximize your coverage. We work with all insurance companies.' },
      { step: 4, title: 'Complete Restoration Work', description: 'Once your claim is approved, we execute full restoration—remove damaged roofing materials, replace damaged decking and structure if needed, install new underlayment and ice/water shield, install new shingles to manufacturer specs, replace damaged gutters and flashing, upgrade ventilation if needed (often covered), and restore roof to better-than-before condition.' },
      { step: 5, title: 'Final Inspection & Warranty Protection', description: 'We conduct final quality inspection, ensure all work meets manufacturer warranty requirements, provide complete documentation for your records and insurance, verify proper ventilation and installation, clean up all debris with magnet sweep, and activate your 50-year shingle warranty + our 10-year workmanship warranty. Your roof is now fully protected!' },
    ],
    benefits: [
      'Emergency response within 2 hours—24/7 availability',
      'Expert insurance claims management—maximize coverage',
      'Drone & thermal imaging documentation',
      'Work with ALL insurance companies',
      '2,000+ successful claims—millions recovered',
      'Free damage assessment & inspection',
      'Meet with adjuster—fight for proper scope',
      'Handle supplements & negotiations',
      'Most claims cover 100% minus deductible',
      'Upgrade opportunities often covered by insurance',
      'Full restoration to manufacturer standards',
      '50-year shingle + 10-year workmanship warranty',
    ],
  },
  {
    id: '9',
    title: 'Insurance Claim Documentation',
    slug: 'insurance-claim-documentation',
    shortDescription: 'Professional roof damage documentation and adjuster support—we help homeowners present accurate information for their insurance claims.',
    description: 'After a storm damages your roof, your insurance company needs accurate documentation to process your claim. We provide professional damage inspection, detailed documentation with photos and measurements, and expert support during the adjuster\'s visit—all at no cost to you. Our role is simple: document roof damage thoroughly and work cooperatively with your insurance adjuster to ensure all damage is properly identified and noted. YOU remain in control of your claim—we simply provide the roofing expertise. We don\'t file claims, negotiate settlements, or act as public adjusters (which requires a special license in Texas). We DO inspect your roof professionally, document every damaged area with photos and measurements, attend the adjuster meeting to point out damage and answer technical questions, provide accurate repair estimates, and ensure nothing is missed. This helps homeowners present complete, accurate information to their insurance company. Free damage inspections for Round Rock, Austin, Georgetown, and all Central Texas after major storms.',
    icon: '📋',
    image: '/images/services/insurance-documentation.jpg',
    process: [
      { step: 1, title: 'Free Professional Roof Inspection', description: 'After a storm, we conduct a comprehensive roof inspection at no cost. We check for hail impacts, wind damage, missing shingles, damaged flashing, gutter damage, and hidden issues. We document everything with photos, measurements, and detailed notes. This inspection helps you understand what damage exists before calling your insurance company.' },
      { step: 2, title: 'Detailed Damage Documentation', description: 'We create a professional damage report with high-resolution photos of every damaged area, measurements and counts (number of hail strikes per square, damaged shingles, etc.), detailed written descriptions of all damage found, and our recommended scope of repair work. This report is YOURS—you can share it with your insurance company to support your claim.' },
      { step: 3, title: 'Adjuster Meeting Support', description: 'When your insurance adjuster schedules their inspection, we meet them on-site at your request. We walk the roof with the adjuster, point out all damaged areas we documented, answer technical roofing questions they have, explain proper repair methods, and ensure all damage is properly noted. The adjuster makes all claim decisions—we simply provide roofing expertise to ensure accurate assessment.' },
      { step: 4, title: 'Accurate Repair Estimates', description: 'We provide detailed, accurate estimates for proper roof repairs using current market pricing and manufacturer-approved materials. This helps you and your adjuster understand the true cost of quality repairs. Your insurance company determines claim coverage—we ensure the estimate reflects proper repair work to manufacturer warranty standards.' },
      { step: 5, title: 'Transparent Communication', description: 'Throughout the process, we keep you informed about what we found, what the adjuster noted, and what proper repairs will involve. If your claim is approved, we can perform the work. If your claim is denied or you choose not to file, there\'s no obligation. We answer your roofing questions and provide honest advice—you make all claim decisions.' },
    ],
    benefits: [
      'FREE professional roof damage inspection',
      'Detailed documentation with photos & measurements',
      'No-cost damage reports for your records',
      'Expert support during adjuster site visits',
      'Ensure all damage is properly identified',
      'Accurate repair estimates—manufacturer standards',
      'Work cooperatively with your adjuster',
      'Answer technical roofing questions',
      'YOU control your claim—we provide expertise',
      'No pressure—damage inspection is always free',
      'Serving Round Rock, Austin, Georgetown, Central Texas',
      'Available after major storms—quick response',
    ],
  },
]

// Service Types for Form
export const SERVICE_TYPES = [
  'Roof Repair',
  'Roof Replacement',
  'New Installation',
  'Storm Damage',
  'Other',
] as const

// Trust Bar / Value Propositions
export const VALUE_PROPS = [
  {
    icon: '✓',
    title: 'CertainTeed Shingle Master',
    description: 'Certified Excellence',
  },
  {
    icon: '�️',
    title: 'Fully Insured',
    description: 'Your protection guaranteed',
  },
  {
    icon: '🚨',
    title: '24/7 Emergency Service',
    description: 'Always here when you need us',
  },
  {
    icon: '🌟',
    title: 'Central Texas Experts',
    description: 'Serving the Austin Metro',
  },
]

// Project Categories
export const PROJECT_CATEGORIES = [
  'All',
  'Commercial',
  'Residential',
  'Metal',
  'Shingle',
  'Tile',
] as const
